---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
<br/>

## Dissertation

Konrad Siek (advisor: Paweł T. Wojciechowski).  
**Distributed Pessimistic Transactional Memory: Algorithms and Properties** (doctoral dissertation).  
Faculty of Computing Science at Poznań University of Technology.  
Submitted June 2016, defended January 2017.  
[[PDF](pub/dissertation.pdf), [TeX](pub/dissertation.tar.gz), [PUT library](https://pp-hip.pfsl.poznan.pl/ipac20/ipac.jsp?session=151C8173887J1.41469&profile=put-library&uri=link=3100007~!756389~!3100001~!3100002&aspect=basic_search&menu=search&ri=8&source=~!bpptest&term=Distributed+Pessimistic+Transactional+Memory%3A+Algorithms+and+Properties+%2F&index=ALTITLE)]

<hr/>

## Papers

Paweł Kobyliński, Konrad Siek, Jan Baranowski, Paweł T. Wojciechowski.  
**Helenos: A Realistic Benchmark for Distributed Transactional Memory**.  
Journal of Software: Practice and Experience.
Volume TBA, issue TBA. 
October 2017.    
[[Wiley](http://onlinelibrary.wiley.com/doi/10.1002/spe.2548/full)]

<hr/>

Konrad Siek, Paweł T. Wojciechowski.  
**Proving Opacity of Transactional Memory with Early Release**.  
Foundations of Computing and Decision Sciences.
Volume 40, issue 4.
December 2015.  
[[De Gruyter](http://www.degruyter.com/view/j/fcds.2015.40.issue-4/fcds-2015-0018/fcds-2015-0018.xml?format=INT>)]

<hr/>

Konrad Siek, Paweł T. Wojciechowski.  
**Atomic RMI: a Distributed Transactional Memory Framework**.  
In proceedings of HLPP 2014: the 7th International Symposium on High-level Parallel Programming and Applications.
International Journal of Parallel Programming, Volume 44, Issue 3, pp 598-619. April 2015.  
[[Springer](http://link.springer.com/article/10.1007/s10766-015-0361-x>)]

<hr/>

Konrad Siek, Paweł T. Wojciechowski.  
**A Formal Design of a Tool for Static Analysis of Upper Bounds on Object Calls in Java**.  
In Proceedings of FMICS 2012: the 17th International Workshop on Formal Methods for Industrial Critical Systems (co-located with FM 2012).  
Lecture Notes in Computer Science Volume 7437, pp 192–206. August 2012.  
[[Springer](https://link.springer.com/chapter/10.1007/978-3-642-32469-7_13), [PDF](pub/fmics12.pdf)]

<br/>

## Short papers

Paweł T. Wojciechowski, Konrad Siek.  
**Atomic RMI 2: Distributed Transactions for Java**.  
In Proceedings of AGERE'16: the 6th International Workshop on Programming Based on Actors, Agents, and Decentralized Control. October 2016.  
[[abstract](https://2016.splashcon.org/event/agere2016-atomic-rmi-2-distributed-transactions-for-java)]

Konrad Siek, Paweł T. Wojciechowski.   
**Brief Announcement: Relaxing Opacity in Pessimistic Transactional Memory**.  
In Proceedings of DISC'14: the 28th International Symposium on Distributed Computing.
October 2014.  
[[PDF](pub/disc14.pdf)]

<hr/>

Konrad Siek, Paweł T. Wojciechowski.  
**Zen and the Art of Concurrency Control: An Exploration of TM Safety Property Space with Early Release in Mind**.  
In Proceedings of WTTM'14: the 6th Workshop on the Theory of Transactional Memory. 
July 2014.  
[[PDF](pub/wttm14.pdf)]

<hr/>

Paweł T. Wojciechowski, Konrad Siek.  
**Having Your Cake and Eating it Too: Combining Strong and Eventual Consistency**.  
In Proceedings of PaPEC 2014: the 1st Workshop on the Principles and Practice of Eventual Consistency. April 2014.  
[[PDF](pub/papec14.pdf)]

<hr/>

Konrad Siek, Paweł T. Wojciechowski.  
**Towards a Fully-Articulated Pessimistic Distributed Transactional Memory** (brief announcement).  
In Proceedings of SPAA 2013: the 25th ACM Symposium on Parallelism in Algorithms and Architectures.
July 2013.  
[[PDF](pub/spaa13.pdf)]

<hr/>

Paweł T. Wojciechowski, Konrad Siek.  
**Rollbacks in Pessimistic Distributed TM**.  
SRDC'13: TRANSFORM Summer School on Research Directions in Distributed Computing. June 2013.  
[[abstract](srdc13-abstract.pdf)]

<hr/>

Paweł T. Wojciechowski, Konrad Siek.  
**Transaction Concurrency Control via Dynamic Scheduling Based on Static Analysis** (extended abstract).  
In Proceedings of WTM 2012: Euro-TM Workshop on Transactional Memory (co-located with ACM SIGOPS EuroSys 2012). April 2012.  
[[abstract](http://www.eurotm.org/action-meetings/wtm2012/program/abstracts#Wojciechowski)]

<hr/>

Konrad Siek, Paweł T. Wojciechowski.  
**Statically Computing Upper Bounds on Object Calls for Pessimistic Concurrency Control** (extended abstract).  
In Proceedings of EC :math:`^2` 2010: Workshop on Exploiting Concurrency Efficiently and Correctly (co-located with CAV 2010). July 2010.  
[[PDF](pub/sw10.pdf)]

<hr/>

## Technical reports

Jan Baranowki, Konrad Siek, Paweł T. Wojciechowski.  
**Analiza Programów Wzorcowych dla Rozproszonej Pamieci Transakcyjnej**.  
Raport RB-3/15. Instytut Informatyki Politechniki Poznańskiej.  
[[PDF](pub/rb-3-15.pdf)]

<hr/>

Martin Witczak, Konrad Siek.  
**Rozproszony System Zarządzania Odtwarzaniem Mediów w Oparciu o Pesymistyczną Pamięć Transakcyjną**.  
Raport RB-4/15. Instytut Informatyki Politechniki Poznańskiej.  
[[PDF](pub/rb-4-15.pdf)]